version: '3'
services:
  # Data base container:
  mongodb:
    build:
      context: .
      dockerfile: ./Dockerfile.mongoDB
    restart: always
    ports:
      - 27017:27017

  # Server container
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mongodb
    # Copies working directory (./auth-service) to specified folder
    volumes:
      - ./:/auth-service
    ports:
      - 3000:3000
    environment:
      # TODO: get from env vars
      - DB_URL=mongodb://user:pass@mongodb:27017
      - NODE_ENV=production

    # TODO: not sure if this is actually been called:
    healthcheck:
      test: curl --fail http://localhost:3000/healthcheck || exit 1
      interval: 30s
      timeout: 10s
      retries: 5